config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home', as: 'home'

  root 'pages#home'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :prizes
  resources :tickets, :except => [:destroy]

  resources :raffles do
    member do
      get 'add_prize'
    end
  end

  devise_for :users

  get 'terms_of_use', to: 'pages#terms_of_use', as: 'terms_of_use'
  get 'show_user_login_form', to: 'pages#show_user_login_form', as: 'show_user_login_form'
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :raffle

  has_one :ticket

  # validates :raffle_id, presence: true

  validates :name, presence: true

  before_destroy do
    self.raffle.active? ? false : true
  end

  def pick_winner
    self.ticket = raffle.pick
    self.save
    self.ticket
  end

  def winner_selected?
    Ticket.where(:prize_id => id).first ? true : false
  end
end

app/models/raffle.rb
class Raffle < ActiveRecord::Base
  include Bootsy::Container

  belongs_to :user

  has_many :tickets

  has_many :prizes
  accepts_nested_attributes_for :prizes, allow_destroy: true

  # validates :description, presence: true

  validates :ticket_price, presence: true, numericality: {:greater_than_or_equal_to => 0}

  validates :ticket_max, :numericality => {:greater_than_or_equal_to => 1, :only_integer => true, :allow_blank => true}

  # validates :user_id, presence: true

  validate :ticket_max_or_end_time
  validate :end_time_is_in_future, :on => :create
  validate :active_raffle_validations

  #spec pending for this
  # validate :at_least_one_prize

  before_destroy :prevent_destroy_if_ticket_has_sold

  #FarmSlugs add presence validation its id_method
  use_farm_slugs id_method: :title

  mount_uploader :image, ImageUploader, dependent: :destroy

  def pick
   tickets.not_winners.sample
  end

  # def active?
  #
  # end

  def tickets_left
    ticket_max - tickets.count if ticket_max
  end

  private

  def prevent_destroy_if_ticket_has_sold
    self.tickets.count > 0 ? false : true
  end

  def ticket_max_or_end_time
    if ticket_max.blank? && end_time.blank?
      errors.add :end_time, "and/or total number of tickets to sell can't be blank"
    end
  end

  def end_time_is_in_future
    errors.add :end_time, "must be in the future" if end_time && end_time < Time.now
  end

  def active_raffle_validations
    if self.active?
      errors.add(:end_time, "can't be changed after a raffle has begun") if changed.include?('end_time')
      errors.add(:ticket_max, "can't be changed after a raffle has begun") if changed.include?('ticket_max')
    end
  end

  # def at_least_one_prize
  #   # errors.add(:prizes, "can't be blank") if self.prizes.count < 1
  # end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :raffle

  belongs_to :prize

  validates :raffle_id, presence: true

  validates :email, presence: true

  before_destroy do
    false
  end

  scope :winners, -> { where.not(prize_id: nil) }
  scope :not_winners, -> { where(prize_id: nil) }

  def winner?
    not self.prize.nil?
  end

  def price
    raffle.ticket_price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :raffles

  validates :terms_of_use, acceptance: true

  # validates :name, :presence => true

  # use_farm_slugs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :terms_of_use
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def terms_of_use

  end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  before_action :set_prize, only: [:show, :edit, :update, :destroy]

  # GET /prizes
  def index
    @prizes = Prize.all
  end

  # GET /prizes/1
  def show
  end

  # GET /prizes/new
  def new
    @prize = Prize.new
  end

  # GET /prizes/1/edit
  def edit
  end

  # POST /prizes
  def create
    @prize = Prize.new(prize_params)

    if @prize.save
      redirect_to @prize, notice: 'Prize was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prizes/1
  def update
    if @prize.update(prize_params)
      redirect_to @prize, notice: 'Prize was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prizes/1
  def destroy
    @prize.destroy
    redirect_to prizes_url, notice: 'Prize was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prize
      @prize = Prize.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def prize_params
      params.require(:prize).permit(:raffle_id, :name, :description, :value, :cost)
    end
end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  before_action :set_raffle, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  def welcome

  end

  #Ajax
  def add_prize
    @raffle = Raffle.new
    @raffle.prizes.new
  end

  # GET /raffles
  def index
    @raffles = Raffle.all
  end

  # GET /raffles/1
  def show
  end

  # GET /raffles/new
  def new
    @raffle = Raffle.new
    @raffle.prizes.new
  end

  # GET /raffles/1/edit
  def edit
  end

  # POST /raffles
  def create
    @raffle = Raffle.new(raffle_params)

    if @raffle.save
      redirect_to @raffle, notice: 'Raffle was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /raffles/1
  def update
    if @raffle.update(raffle_params)
      redirect_to @raffle, notice: 'Raffle was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /raffles/1
  def destroy
    @raffle.destroy
    redirect_to raffles_url, notice: 'Raffle was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raffle
      @raffle = Raffle.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def raffle_params
      params.require(:raffle).permit(:user_id, :title, :description, :image, :end_time, :ticket_max, :ticket_price,
                                     :image, :remote_image_url, :image_cache,
                                     :bootsy_image_gallery_id
                                    )
    end
end

app/controllers/registrations_controller.rb
# class RegistrationsController < Devise::RegistrationsController
#   respond_to :json
# end

app/controllers/sessions_controller.rb
# class SessionsController < Devise::SessionsController
#   respond_to :json, :js
#
#   # def new
#   #   render 'devise/sessions/new'
#   # end
# end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  # def destroy
  #   @ticket.destroy
  #   redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ticket_params
      params.require(:ticket).permit(:email, :winner, :raffle_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FarmTools::ErrorsHelper
  include HtmlParts
  include HtmlTools
  include TwitterExpress


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnyRaffle</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'parts/top_nav' %>
  <%= render 'parts/the_flash' %>
  <%= yield %>

  <script>
    doReadyMethods();
  </script>
</body>
</html>

app/views/pages/_show_user_login_form.js.erb
$('body').append("<%= j render partial: 'pages/partials/login_form' %>");
$('#express_modal').modal('show');

app/views/pages/home_blocks/_one.html.erb
<div id="home_block_1" class="content_block">
  <% if user_signed_in? -%>
    <%= render partial: 'users/dashboard' %>

  <% else -%>
    <%= render partial: 'devise/registrations/new' %>
  <% end -%>
</div>

app/views/pages/partials/_login_form.html.erb
d<div id="new_user_session">
  <%= form_for :user, url: 'users/sign_in' do |f| %>
    <div class="form-group">
      <%= f.label :email, class: 'control-label' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, class: 'control-label' %>
      <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Login', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/pages/partials/_terms_of_use.html.erb
<%= express_modal "AnyRaffle's Terms of Use" do %>
  Terms of use......
<% end %>

app/views/pages/terms_of_use.js.erb
$('body').append("<%= j render partial: 'pages/partials/terms_of_use' %>");
$('#express_modal').modal('show');

app/views/parts/_the_flash.html.erb
<% if alert -%>
  <div class="flash alert container">
    <div class="row">
      <div class="col-xs-12">
        <button class="close">x close</button>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <h4><%= alert %></h4>
      </div>
    </div>
  </div>
<% end -%>

<% if notice -%>
  <div class="flash notice container">
    <div class="row">
      <div class="col-xs-12">
        <button class="close">x close</button>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <h4><%= notice %></h4>
      </div>
    </div>
  </div>
<% end -%>

<% if notice || alert -%>
  <script>
    $('.flash .close').click(function(){
      $(this).closest('.flash').slideUp(1000);
    })
  </script>
<% end -%>

app/views/parts/_top_nav.html.erb
<div id='top_nav' class='navbar navbar-inverse' role='navigation'>
  <div class="container">
    <div class='navbar-header'>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top_nav_body">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'AnyRaffle', root_path, :class => 'navbar-brand' %>
    </div>

    <div id='top_nav_body' class='collapse navbar-collapse'>
      <ul class='nav navbar-nav navbar-right'>
        <!--<li classs="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--&lt;!&ndash;<li class="divider"></li>&ndash;&gt;-->
          <!--</ul>-->
        <!--</li>-->

        <!--<li>-->
          <%#= link_to('New Raffle', new_raffle_path) %>
        <!--</li>-->
        <li>
          <% if user_signed_in? -%>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else -%>
              <%= link_to 'Login', new_user_session_path, remote: true %>
          <% end -%>
        </li>
      </ul>
    </div>
  </div>
</div>


<script>
//  function padBodyForTopNav(){
//    $('body').css('padding-top', $('#top_nav').height() + 1);
//
//    $(window).resize(function(){
//      $('body').css('padding-top', $('#top_nav').height() + 1);
//    })
//  }

//  ready_methods.push(padBodyForTopNav);
</script>

app/views/prizes/_embedded_form.html.erb
<div class="row prize">
  <%= form_builder.fields_for :prizes, :child_index => Time.now.to_i do |prize_fields| %>
    <div class="col-sm-3">
      <div class="form-group">
        <%= prize_fields.label :name, :class => 'control-label' %>
        <%= prize_fields.text_field :name, class: 'form-control' %>
      </div>
    </div><!-- col -->
    <div class="col-sm-5">
      <div class="form-group">
        <%= prize_fields.label :description, class: 'control-label' %>
        <%= prize_fields.text_field :description, class: 'form-control' %>
      </div>
    </div><!-- col -->
    <div class="col-sm-2">
      <div class="form-group">
        <%= prize_fields.label :value, class: 'control-label' %>
        <%= prize_fields.text_field :value, class: 'form-control' %>
      </div>
    </div><!-- col -->
    <div class="col-sm-2">
      <%= prize_fields.label :cost, 'Actual cost', class: 'control-label' %>
      <%= prize_fields.text_field :cost, class: 'form-control' %>
    </div><!-- col -->
  <% end %>
</div><!-- row -->

app/views/prizes/_form.html.erb
<%= form_for(@prize) do |f| %>
  <% if @prize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prize.errors.count, "error") %> prohibited this prize from being saved:</h2>

      <ul>
      <% @prize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.number_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prizes/edit.html.erb
<h1>Editing Prize</h1>

<%= render 'form' %>

<%= link_to 'Show', @prize %> |
<%= link_to 'Back', prizes_path %>

app/views/prizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prizes</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Name</th>
      <th>Description</th>
      <th>Value</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prizes.each do |prize| %>
      <tr>
        <td><%= prize.ticket_id %></td>
        <td><%= prize.name %></td>
        <td><%= prize.description %></td>
        <td><%= prize.value %></td>
        <td><%= prize.cost %></td>
        <td><%= link_to 'Show', prize %></td>
        <td><%= link_to 'Edit', edit_prize_path(prize) %></td>
        <td><%= link_to 'Destroy', prize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prize', new_prize_path %>

app/views/prizes/new.html.erb
<h1>New Prize</h1>

<%= render 'form' %>

<%= link_to 'Back', prizes_path %>

app/views/prizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @prize.ticket_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @prize.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prize.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @prize.value %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @prize.cost %>
</p>

<%= link_to 'Edit', edit_prize_path(@prize) %> |
<%= link_to 'Back', prizes_path %>

app/views/raffles/_form.html.erb
<%= form_for(@raffle) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= error_explanation(@raffle) %>
    </div><!-- col -->
  </div><!-- row -->

  <%= f.hidden_field :user_id, value: current_user.id if user_signed_in? -%>

  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :title, class: 'control-label' %>
        <%#= f.text_field :title, class: 'form-control', required: true %>
        <%= f.text_field :title, class: 'form-control'%>
      </div>
    </div><!-- col -->

    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :ticket_price, class: 'control-label' %>
        <%= f.text_field :ticket_price, class: 'form-control' %>
      </div>
    </div><!-- col -->

    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :paypal_email, class: 'control-label' %>
        <%= f.email_field :paypal_email, :class => 'form-control' %>
      </div>
    </div><!-- col -->
  </div><!-- row -->
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :end_time, class: 'control-label'  %>
        <div id="dt_picker" class="input-group date">
          <%= f.text_field :end_time, class: 'form-control' %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div><!-- input-group-->
      </div><!-- form-group -->
    </div><!-- col -->

    <div class="col-sm-2">
      <h2 class="text-center"> Or
        <%#= express_popover('Or', 'You may specify a time to end the raffle or a total number of tickets to sell
                                   before the raffle ends. Or you may specify both, in which case the event that happens
                                    first will end the raffle', ) %>
      </h2>
    </div><!-- col -->
    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :ticket_max, 'Total number of tickets to sell', class: 'control-label' %>
        <%= f.text_field :ticket_max, class: 'form-control' %>
      </div>
    </div><!--col -->
  </div><!-- row -->
  <div class="row">
    <div class="col-sm-12">
      <div id="raffle_description_group" class="form-group">
        <%= f.label :description, class: 'control-label' %>
        <%= f.bootsy_area :description, class: 'form-control' %>
      </div>
    </div><!-- col -->
  </div><!-- row -->
  <%= image_select f, :image %><!-- row -->

  <div class="prizes">
    <div class="row">
      <div class="col-md-12">
        <h2>Prizes</h2>
      </div>
    </div>
    <%= render partial: 'prizes/embedded_form', :locals => {:form_builder => f} %><!-- row -->

  </div><!-- prizes -->

  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div><!-- col -->
  </div><!-- row -->
<% end %><!-- form -->

<script>
  $(function(){
    $('#dt_picker').datetimepicker();
    $('.express_popover').popover();
  });
</script>

app/views/raffles/edit.html.erb
<div class="container" id="edit_raffle">
  <h1>Editing <%= link_to @raffle.title, @raffle %></h1>
  <%= render 'form' %>
</div>

app/views/raffles/index.html.erb
<div class="container">
  <h1>Raffles</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th>Ends</th>
      <th>Tickets Left</th>
      <th>Ticket price</th>
    </tr>
    </thead>

    <tbody>
    <% @raffles.each do |raffle| %>
      <tr>
        <td><%= link_to raffle.title, raffle %></td>
        <td><%= image_tag raffle.image.url(:thumb), width: '50px' %></td>
        <td><%= raffle.end_time.strftime('%D') if raffle.end_time -%></td>
        <td>
          <% if raffle.ticket_max -%>
            <%= raffle.ticket_max - raffle.tickets.count %>
          <% end -%>
        </td>
        <td><%= number_to_currency(raffle.ticket_price) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/raffles/new.html.erb
<div id="new_raffle" class="container">
  <h1>New Raffle</h1>
  <%= render 'form' %>
</div>

app/views/raffles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @raffle.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @raffle.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @raffle.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @raffle.image %>
</p>

<p>
  <strong>End time:</strong>
  <%= @raffle.end_time %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @raffle.slug %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @raffle.ticket_price %>
</p>

<%= link_to 'Edit', edit_raffle_path(@raffle) %> |
<%= link_to 'Back', raffles_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.check_box :winner %>
  </div>
  <div class="field">
    <%= f.label :raffle_id %><br>
    <%= f.number_field :raffle_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Winner</th>
      <th>Raffle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.email %></td>
        <td><%= ticket.winner %></td>
        <td><%= ticket.raffle_id %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @ticket.email %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @ticket.winner %>
</p>

<p>
  <strong>Raffle:</strong>
  <%= @ticket.raffle_id %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/_dashboard.html.erb
<div id="user_dashboard">
  <% if current_user.raffles.count > 0 -%>
    <ul class="raffle_list">
      <h3>Your Raffles</h3>
      <% current_user.raffles.each do |r| -%>
        <li>
          <%= link_to r.title, r %>
        </li>
      <% end -%>
    </ul>
  <% else -%>
    <div>
      Thank you for signing up. After you create your first Raffle, they will be listed here.
    </div>
  <% end -%>

</div>